CREATE TABLE IF NOT EXISTS dd_generated_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  deal_id BIGINT UNSIGNED NOT NULL,
  item_type VARCHAR(120) NOT NULL,
  title VARCHAR(255) NOT NULL,
  prompt_summary TEXT NULL,
  generated_text MEDIUMTEXT NOT NULL,
  model VARCHAR(120) NULL,
  item_status VARCHAR(80) NOT NULL DEFAULT 'Generated',
  created_by VARCHAR(150) NULL,
  reviewed_by VARCHAR(150) NULL,
  reviewed_at DATETIME NULL,
  approved_by VARCHAR(150) NULL,
  approved_at DATETIME NULL,
  used_at DATETIME NULL,
  rejected_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_dd_generated_public_id (public_id),
  KEY idx_dd_generated_deal_created (deal_id, created_at),
  KEY idx_dd_generated_type_status (item_type, item_status),
  CONSTRAINT fk_dd_generated_deal FOREIGN KEY (deal_id) REFERENCES dd_deals(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
