CREATE TABLE IF NOT EXISTS dd_transaction_tasks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  deal_id BIGINT UNSIGNED NOT NULL,
  category VARCHAR(80) NOT NULL,
  task_name VARCHAR(255) NOT NULL,
  waiting_on_entity_type VARCHAR(80) NULL,
  waiting_on_name VARCHAR(200) NULL,
  office_contact_name VARCHAR(200) NULL,
  office_contact_role VARCHAR(120) NULL,
  office_contact_phone VARCHAR(80) NULL,
  office_contact_email VARCHAR(200) NULL,
  status VARCHAR(80) NOT NULL DEFAULT 'Waiting',
  priority VARCHAR(40) NOT NULL DEFAULT 'Normal',
  due_date DATE NULL,
  last_contacted_at DATETIME NULL,
  verified_at DATETIME NULL,
  completed_at DATETIME NULL,
  verification_notes TEXT NULL,
  notes TEXT NULL,
  created_by VARCHAR(150) NULL,
  updated_by VARCHAR(150) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_dd_transaction_tasks_public_id (public_id),
  KEY idx_dd_tasks_deal_status (deal_id, status),
  KEY idx_dd_tasks_category (category),
  KEY idx_dd_tasks_due_date (due_date),
  CONSTRAINT fk_dd_tasks_deal FOREIGN KEY (deal_id) REFERENCES dd_deals(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
