CREATE TABLE IF NOT EXISTS dd_email_messages (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  deal_id BIGINT UNSIGNED NOT NULL,
  email_type VARCHAR(120) NOT NULL,
  recipient_role VARCHAR(120) NOT NULL,
  to_name VARCHAR(200) NULL,
  to_email VARCHAR(200) NOT NULL,
  cc_email TEXT NULL,
  subject VARCHAR(255) NOT NULL,
  body MEDIUMTEXT NOT NULL,
  email_status VARCHAR(80) NOT NULL DEFAULT 'Draft',
  provider_message_id VARCHAR(255) NULL,
  sent_at DATETIME NULL,
  failed_at DATETIME NULL,
  failure_reason TEXT NULL,
  created_by VARCHAR(150) NULL,
  sent_by VARCHAR(150) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_dd_email_messages_public_id (public_id),
  KEY idx_dd_email_deal_status (deal_id, email_status),
  KEY idx_dd_email_recipient (to_email),
  CONSTRAINT fk_dd_email_messages_deal FOREIGN KEY (deal_id) REFERENCES dd_deals(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
