CREATE TABLE IF NOT EXISTS dd_communication_log (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  deal_id BIGINT UNSIGNED NOT NULL,
  communication_type VARCHAR(80) NOT NULL DEFAULT 'Phone',
  entity_type VARCHAR(100) NULL,
  entity_name VARCHAR(200) NULL,
  contact_name VARCHAR(200) NULL,
  contact_role VARCHAR(120) NULL,
  contact_phone VARCHAR(80) NULL,
  contact_email VARCHAR(200) NULL,
  direction VARCHAR(40) NOT NULL DEFAULT 'Outgoing',
  communication_at DATETIME NOT NULL,
  summary TEXT NOT NULL,
  confirmed_items TEXT NULL,
  follow_up_needed TEXT NULL,
  follow_up_due_date DATE NULL,
  created_by VARCHAR(150) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_dd_communication_public_id (public_id),
  KEY idx_dd_comm_deal_time (deal_id, communication_at),
  KEY idx_dd_comm_followup_due (follow_up_due_date),
  CONSTRAINT fk_dd_communication_deal FOREIGN KEY (deal_id) REFERENCES dd_deals(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
